add the redirectUrl argument and use it in loginUrl
mitodl/mit-open-login-button pull request #7
Opened 2024-02-05 21:58 UTC by gumaerc

### What are the relevant tickets?
Closes https://github.com/mitodl/mit-open-login-button/issues/6

### Description (What does it do?)
This PR adds a new argument to `initLoginButton`, `redirectUrl`. This string argument is simply passed through as the `redirect_url` query string parameter to the login endpoint. If the domain of the redirect URL is set in the `SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS` setting on the instance of `mit-open` that you are hitting, then you will be redirected back to that URL after logging in.

### How can this be tested?
 - You will need to make a slight alteration to the code before testing this, as at the time of writing https://github.com/mitodl/mit-open-login-button/pull/5 has not been merged and it fixes an issue with the `/users/me` endpoint:
```
Replace:
const apiUrl = `${parsedBaseUrl.origin}/api/v0/users/me?format=json`
With:
const apiUrl = `${parsedBaseUrl.origin}/api/v0/users/me/?format=json`
```
 - In order to test this, you will need a running instance of [`mit-open`](https://github.com/mitodl/mit-open). Follow the instructions in the `mit-open` readme for initial setup. You will need an account in your local instance for this to work. Your instance of `mit-open` should be accessible at `http://od.odl.local:8063`. You will need to set the following environment variables:
```
CORS_ALLOWED_ORIGINS=["http://ocw.odl.local:3000"]
SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS=["ocw.odl.local:3000"]
```
 - You will also need `ocw-hugo-themes` (https://github.com/mitodl/ocw-hugo-themes) set up locally, running a course using `yarn start course`. Follow the readme there for basic setup instructions and make sure you can start up a course. After you have that working, check out the `cg/add-mit-open-login-button` branch. Assuming you have cloned this repo, run `yarn add /path/to/mit-open-login-button` to add your local copy of the code for this to your locally running `ocw-hugo-themes`. This is necessary because the package is not yet published to NPM. You will also need an entry in your `hosts` file that points the `ocw.odl.local` domain to `127.0.0.1`.
 - Once you have all this running, make sure you are logged out of your local instance of `mit-open`
 - Back in your locally running OCW course site, you should see a Login button in the upper right. Click this button and log in to your locally running `mit-open`
 - After you have logged in, you will be sent to http://od.odl.local:8063
 - Go back to your locally running OCW site at http://ocw.odl.local:3000 and confirm that you see `Logged in as: username` with your username in place of `username`
 - In another tab, log out of your locally running `mit-open`
 - Verify that the login button reappears

2024-02-06 15:42 UTC, rhysyngsun requested changes
Code review

2024-02-06 15:42 UTC, rhysyngsun commented on index.js
> +    redirectUrl !== "" ? `?redirect_url=${redirectUrl}` : ""
I think this needs to be encoded:

```suggestion
    redirectUrl !== "" ? `?redirect_url=${encodeURIComponent(redirectUrl)}` : ""
```

2024-02-06 19:32 UTC, gumaerc commented on index.js
> +    redirectUrl !== "" ? `?redirect_url=${redirectUrl}` : ""
Thanks, I implemented your suggestion

2024-02-08 20:49 UTC, gumaerc commented
@rhysyngsun This is ready for another look

2024-02-09 23:05 UTC, rhysyngsun commented
Note: I'm not sure if there will be docs elsewhere but the instructions were missing the step to set the environment variable `MIT_OPEN_BASEURL` for the ocw-hugo-themes process.

2024-02-12 16:01 UTC, gumaerc commented
> Note: I'm not sure if there will be docs elsewhere but the instructions were missing the step to set the environment variable `MIT_OPEN_BASEURL` for the ocw-hugo-themes process.

Yea, sorry about that. @ChristopherChudzicki merged a PR into my branch for this that adds that variable and I forgot to update the testing instructions.

2024-02-12 19:42 UTC, rhysyngsun approved these changes
LGTM

2024-02-12 19:46 UTC, merged